sudo: false
dist: trusty
language: python
python:
- '3.5'
env:
- TOX_ENV=tan1uan5
- TOX_ENV=flake8
branches:
  only:
  - master
  - "/\\d+\\.\\d+\\.\\d+/"
before_script:
- pip install tox coveralls
script:
- tox -e $TOX_ENV
after_success:
- coverage report
- coveralls

