version: '3.5'

services:
  miasenn:
    build: .
    command: gunicorn miasenn.wsgi --log-level debug -b 0.0.0.0:8000
    networks:
      - default
      - nginx-bridge
    environment:
      VIRTUAL_HOST: "miasenn.itaigi.tw"
      LETSENCRYPT_HOST: "miasenn.itaigi.tw"
      LETSENCRYPT_EMAIL: "ithuan@ithuan.tw"
    restart: always
  leku:
    image: sih4sing5hong5/itaigi-leku
    command: gunicorn hok8bu7.wsgi --log-level debug -b 0.0.0.0:8000
    networks:
      - default
      - nginx-bridge
    expose:
      - 8000
    environment:
      VIRTUAL_HOST: "leku.itaigi.tw"
      LETSENCRYPT_HOST: "leku.itaigi.tw"
      LETSENCRYPT_EMAIL: "ithuan@ithuan.tw"
    restart: always

networks:
  nginx-bridge:
    external: true
