version: '3.5'

services:
  gunicorn:
    build: .
    command: gunicorn miasenn.wsgi --log-level debug -b 0.0.0.0:8000
    depends_on:
      - pyro4
    ports:
      - "8000:8000"
    expose:
      - "8000"
    environment:
      VIRTUAL_HOST: "miasenn.xn--v0qr21b.xn--kpry57d"
      VIRTUAL_PORT: 8000
